<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;UnitTests</Configurations>
    <Title>BlazorCssTransitions</Title>
    <PackageIcon>nuget_icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/DDaarcon/BlazorCssTransitions</RepositoryUrl>
    <PackageTags>blazor;transitions;hybrid</PackageTags>
    <PackageProjectUrl>https://github.com/DDaarcon/BlazorCssTransitions</PackageProjectUrl>
    <Description>Easily define basic animations and transitions entirely in C#.</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Version>0.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\animatedVisibilityTransitions\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\assets\nuget_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
