<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;UnitTests</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNext.Threading" Version="6.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\animatedVisibilityTransitions\" />
  </ItemGroup>

</Project>
